apiVersion: v1 
kind: Pod 
metadata: 
  name: random-number-generator 
spec: 
  containers: 
  - image: alpine
    name: alpine
    command: ["/bin/sh", "-c"]
    args: ["echo '123' > /karan/dbTable"] 
    volumeMounts: 
    - mountPath: /karan
      name: data-volume ##map

  volumes: 
  - name: data-volume ##map
    hostPath: 
      path: /data ##on host machine
      type: directory 
