apiVersion: v1 
kind: Pod 
metadata: 
  name: random-number-generator 
spec: 
  containers: 
  - image: alpine
    name: alpine
    command: ["/bin/sh", "-c"]
    args: ["echo '123' > dbTable"] 

  volumes: 
  - name: data-volume
    hostPath: 
      path: /data ##on host machine
      type: directory 
